name: Integración y entrega continua

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      NOMBRES: "Enrique"
      APELLIDOS: "Pérez Pereyra" 
      EDAD: "35"
      VERSION_PROYECTO: "3.0"  

    steps:
      # Step 1: Presentación
      - name: presentación
        run: |
          echo "Nombres: $NOMBRES"
          echo "Apellidos: $APELLIDOS"
          echo "Edad: $EDAD"
      
      # Step 2: Datos generales
      - name: datos generales
        run: echo "carrera de ingeniería de sistemas"
      
      # Step 3: Variables de entorno secretas
      - name: variables de entorno secretas
        run: |
          echo "user: ${{ secrets.user }}"
          echo "password: ${{ secrets.PASSWORD }}"
      
      # Step 4: Variables abiertas
      - name: variables abiertas
        run: |
          echo "Imprimiento Versión de mi proyecto: $VERSION_PROYECTO"